name: Publish Docker image

on:
  push:
    tags:
    - 'v*'

jobs:
  push_to_registries:
    name: Push Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build and Publish
        run: |
          mkdir ./_compile_self/aarch64
          mkdir ./_compile_self/amd64
          dotnet restore "./src/BRouteMqttApp/BRouteMqttApp.csproj"
          dotnet publish "./src/BRouteMqttApp/BRouteMqttApp.csproj" -r linux-musl-arm64 -p:PublishSingleFile=true --self-contained false -c Release -o "./_compile_self/aarch64" --no-restore
          dotnet publish "./src/BRouteMqttApp/BRouteMqttApp.csproj" -r linux-musl-x64 -p:PublishSingleFile=true --self-contained false -c Release -o "./_compile_self/amd64" --no-restore

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Extract metadata (tags, labels) for Docker aarch64
        id: meta-aarch64
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/hsakoh/broutemqtt-aarch64
          tags: |
            latest
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}/

      - name: Build and push Docker images aarch64
        id: push-aarch64
        uses: docker/build-push-action@v6
        with:
          context: ./_compile_self
          platforms: linux/arm64
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/aarch64-base:latest
            BUILD_ARCH=aarch64
          push: true
          tags: ${{ steps.meta-aarch64.outputs.tags }}
          labels: ${{ steps.meta-aarch64.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker amd64
        id: meta-amd64
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/hsakoh/broutemqtt-amd64
          tags: |
            latest
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}/

      - name: Build and push Docker images amd64
        id: push-amd64
        uses: docker/build-push-action@v6
        with:
          context: ./_compile_self
          platforms: linux/amd64
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/amd64-base:latest
            BUILD_ARCH=amd64
          push: true
          tags: ${{ steps.meta-amd64.outputs.tags }}
          labels: ${{ steps.meta-amd64.outputs.labels }}
